drop TABLE UKE_EVENT_LOG ;
CREATE TABLE UKE_EVENT_LOG 
(
  PAT_ID NUMBER(10, 0) 
, TUMOR_ID VARCHAR2(2 BYTE) 
, DATENART VARCHAR2(20 BYTE)
, DOKUMENTLFDNR NUMBER 
, EVENT_DATUM DATE NOT NULL 
, EVENT_KLASSE VARCHAR2(254 BYTE) 
, EVENT_TYP VARCHAR2(254 BYTE) 
, EVENT VARCHAR2(254 BYTE) 
, EVENT_WERTE VARCHAR2(254 BYTE) 
, EVENT_BEMERKUNG VARCHAR2(254 BYTE) 
, FK_BENUTZER_ID VARCHAR2(30 BYTE) 
) 
LOGGING 
TABLESPACE GTDS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 458752 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX I1_UKE_EVENT_LOG ON UKE_EVENT_LOG (PAT_ID ASC,TUMOR_ID ASC, DATENART ASC, DOKUMENTLFDNR ASC) 
LOGGING 
TABLESPACE GTDS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 196608 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

