-- Gyn und Mamma noch separieren
insert into AW_KLASSE (KLASSIERUNG_ID,CODE,TEXT30,KLASSIERUNG_QUELLE) values (9,53,'Gynaecology','UKE');
insert  into AW_KLASSE (KLASSIERUNG_ID,CODE,TEXT30,KLASSIERUNG_QUELLE) values (9,56,'Breast','UKE');

update AW_KLASSE
set ORDNUNG=999
where CODE=50
and KLASSIERUNG_ID=9
and KLASSIERUNG_QUELLE='UKE';
commit;

--Insert Breast & Gynaecology
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,A_BIS,KLASSIERUNG_QUELLE) values (9,50,'50%','80000','91899','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,A_BIS,KLASSIERUNG_QUELLE) values (9,50,'48%','80000','95699','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,A_BIS,KLASSIERUNG_QUELLE) values (9,50,'51%','80000','95699','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,A_BIS,KLASSIERUNG_QUELLE) values (9,50,'52%','80000','95699','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,A_BIS,KLASSIERUNG_QUELLE) values (9,50,'53%','80000','95699','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,A_BIS,KLASSIERUNG_QUELLE) values (9,50,'54%','80000','95699','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,A_BIS,KLASSIERUNG_QUELLE) values (9,50,'55%','80000','95699','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,A_BIS,KLASSIERUNG_QUELLE) values (9,50,'56%','80000','95699','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,A_BIS,KLASSIERUNG_QUELLE) values (9,50,'57%','80000','95699','UKE');

--Insert Breast
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,A_BIS,KLASSIERUNG_QUELLE) values (9,56,'50%','80000','91899','UKE');

--Insert Gynaecology
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,A_BIS,KLASSIERUNG_QUELLE) values (9,53,'48%','80000','95699','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,A_BIS,KLASSIERUNG_QUELLE) values (9,53,'51%','80000','95699','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,A_BIS,KLASSIERUNG_QUELLE) values (9,53,'52%','80000','95699','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,A_BIS,KLASSIERUNG_QUELLE) values (9,53,'53%','80000','95699','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,A_BIS,KLASSIERUNG_QUELLE) values (9,53,'54%','80000','95699','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,A_BIS,KLASSIERUNG_QUELLE) values (9,53,'55%','80000','95699','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,A_BIS,KLASSIERUNG_QUELLE) values (9,53,'56%','80000','95699','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,A_BIS,KLASSIERUNG_QUELLE) values (9,53,'57%','80000','95699','UKE');

commit;
--delete from AW_KLASSENBEDINGUNG where KLASSIERUNG_ID =9 and KLASSIERUNG_QUELLE='UKE';commit;