drop MATERIALIZED VIEW AW_KLASSEN_ALLE
;

CREATE VIEW AW_KLASSEN_ALLE
as
select distinct b.LIKE_KRITERIUM,k.CODE KLASSE_CODE,k.ORDNUNG KLASSE_ORDNUNG,k.TEXT30 KLASSE_KURZ,k.TEXT255 KLASSE_LANG,k.BESCHREIBUNG KLASSE_BESCHREIBUNG,
k.KLASSIERUNG_ID,k.KLASSIERUNG_QUELLE,a.KURZBEZEICHNUNG KLASSIERUNG_KURZ,a.BEZEICHNUNG KLASSIERUNG_BEZEICHNUNG
from  AW_KLASSENBEDINGUNG b

inner join AW_KLASSE k
on k.code=b.code
and k.klassierung_id=b.KLASSIERUNG_ID
and b.KLASSIERUNG_QUELLE=k.KLASSIERUNG_QUELLE

inner join AW_KLASSIERUNG A
on a.ID=k.KLASSIERUNG_ID;