

Insert into FACHRICHTUNGEN (GEBIET_ID,KUERZEL,BEZEICHNUNG) VALUES('22','ANAE','Anästhesiologie');
Insert into FACHRICHTUNGEN (GEBIET_ID,KUERZEL,BEZEICHNUNG) VALUES('23','BIO','Biochemie');
Insert into FACHRICHTUNGEN (GEBIET_ID,KUERZEL,BEZEICHNUNG) VALUES('24','ACH','Allgemeine Chirurgie');
Insert into FACHRICHTUNGEN (GEBIET_ID,KUERZEL,BEZEICHNUNG) VALUES('25','TCH','Thoraxchirurgie');

Insert into FACHRICHTUNGEN (GEBIET_ID,KUERZEL,BEZEICHNUNG) VALUES('27','HUM','Humangenetik');
Insert into FACHRICHTUNGEN (GEBIET_ID,KUERZEL,BEZEICHNUNG) VALUES('28','NEU','Neurologie');
Insert into FACHRICHTUNGEN (GEBIET_ID,KUERZEL,BEZEICHNUNG) VALUES('29','NEUP','Neuropathologie');
Insert into FACHRICHTUNGEN (GEBIET_ID,KUERZEL,BEZEICHNUNG) VALUES('30','PATH','Pathologie');

commit;

insert into AW_KLASSIERUNG (ID,KURZBEZEICHNUNG,BEZEICHNUNG,QUELLE,BESCHREIBUNG) values (12,'Facharzt-Entitaeten','Zuordnung ICD der Diagnose <-> Facharzt','UKE','Zuordnung für Follow-Up anfragen bei bestimmten Arztgruppen');
commit;

Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,10,'ACH','Allgemeine Chirurgie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,20,'1','Allgemeinmedizin','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,30,'ANAE','Anästhesiologie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,40,'AUG','Augenheilkunde','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,50,'BIO','Biochemie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,60,'DIA','Diabetologie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,70,'2','Frauenheilkunde und Geburtshilfe','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,80,'GAS','Gastroenterologie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,90,'HNO','Hals- Nasen- Ohrenheilkunde','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,100,'IHA','Hämatologie und Onkologie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,110,'DER','Haut- und Geschlechtskrankheiten','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,120,'HUM','Humangenetik','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,130,'IM','Innere Medizin','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,140,'KAR','Kardiologie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,150,'MKG','Mund-Kiefer-Gesichtschirurgie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,160,'NAT','Naturheilverfahren','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,170,'NCH','Neurochirurgie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,180,'NEU','Neurologie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,190,'NEUP','Neuropathologie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,200,'NUK','Nuklearmedizin','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,210,'ORT','Orthopädie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,220,'PATH','Pathologie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,230,'PNE','Pneumologie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,240,'RAD','Radiologie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,250,'RHE','Rheumatologie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,260,'STR','Strahlentherapie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,270,'TCH','Thoraxchirurgie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,280,'CUN','Unfallchirurgie','UKE');
Insert into AW_KLASSE(KLASSIERUNG_ID,CODE,TEXT30,Text255,KLASSIERUNG_QUELLE) values(12,290,'URO','Urologie','UKE');

commit;
select * from AW_KLASSENBEDINGUNG where KLASSIERUNG_ID=2 and KLASSIERUNG_QUELLE='UKE' and (CODE=50 or code =40);

--GYN
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,KLASSIERUNG_QUELLE)
  select 12,70,LIKE_KRITERIUM,'UKE' from AW_KLASSENBEDINGUNG where KLASSIERUNG_ID=2 and KLASSIERUNG_QUELLE='UKE' and (CODE=50 or code =40);
  
--DARM
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,KLASSIERUNG_QUELLE)
  select 12,80,LIKE_KRITERIUM,'UKE' from AW_KLASSENBEDINGUNG where KLASSIERUNG_ID=2 and KLASSIERUNG_QUELLE='UKE' and CODE=30 ;

--HNO
--insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,KLASSIERUNG_QUELLE)
  --select 12,90,LIKE_KRITERIUM,'UKE' from AW_KLASSENBEDINGUNG where KLASSIERUNG_ID=2 and KLASSIERUNG_QUELLE='UKE' and CODE=30 ;
  commit;