insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,KLASSIERUNG_QUELLE) values (8, 140,'80%','87206','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,KLASSIERUNG_QUELLE) values (8, 140,'80%','87306','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,KLASSIERUNG_QUELLE) values (8, 170,'49%','96983','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,KLASSIERUNG_QUELLE) values (8, 170,'84%','97003','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,KLASSIERUNG_QUELLE) values (8, 170,'42%','97013','UKE');
insert into AW_KLASSENBEDINGUNG (KLASSIERUNG_ID,CODE,LIKE_KRITERIUM,A_VON,KLASSIERUNG_QUELLE) values (8, 160,'44%','88023','UKE');


commit;