
select distinct p.PROTOKOLL_ID,p.LANG_BEZEICHNUNG,p.AKTIV,m.ABDA_NUMMER,m.GENERIC_NAME,m.EIGENE_BEZEICHNUNG
from PROtokoll p
inner Join PROTOKOLL_MEDIKAMENT pm
on p.PROTOKOLL_ID=pm.FK_PROTOKOLLPROTOK
inner join MEDIKAMENT m
on m.ABDA_NUMMER=pm.FK_MEDIKAMENTMEDIK
where p.LANG_BEZEICHNUNG like '%Irinot%'

order by p.PROTOKOLL_ID;

select * from INTERNISTISCHE_THERAPIE where FK_PROTOKOLLPROTOK=427; --Patid: 9575 Innere: 11
select * from ZYKLUS_GESAMT_MEDI where FK_MEDIKAMENTABDA='123'; --PATID: 9575 INNERE: 11 + 12 / PAT: 23515 INNERE:3