insert into UKE_EVENT_LOG (PAT_ID,TUMOR_ID,DATENART,DOKUMENTLFDNR,EVENT_DATUM,EVENT_KLASSE,EVENT_TYP,EVENT,FK_BENUTZER_ID)
select PAT_ID, TUMOR_ID,DATENART,DOKUMENTLFDNR,DATUM,'BERICHTE',ART_DES_BRIEFES,'erstellt',FK_BENUTZER_ID
from 
BERICHTE
where ART_DES_BRIEFES in ('UKE_KKR_Datenanfrage','UKE_KKR_Datenanfrage_Erinnerung');
commit;